---
name: Math-Symbolic-Custom-Pattern
version: 2.00
author:
  - 'Steffen Mueller <symbolic-module at steffen-mueller dot net>'
abstract: Pattern matching on Math::Symbolic trees
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Clone: 0
  Math::Symbolic: 0.510
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
provides:
  Math::Symbolic::Custom::Pattern:
    file: lib/Math/Symbolic/Custom/Pattern.pm
    version: 2.00
  Math::Symbolic::Custom::Pattern::Export:
    file: lib/Math/Symbolic/Custom/Pattern/Export.pm
    version: 1.20
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
