--- #YAML:1.0
name: Math-Symbolic-Custom-Pattern
version: 1.10
author:
  - |-
    Steffen Mueller <symbolic-module at steffen-mueller dot net>
abstract: Pattern matching on Math::Symbolic trees
license: perl
requires:
  Math::Symbolic: 0.162
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
build_requires:
  Test::More: 0
provides:
  Math::Symbolic::Custom::Pattern:
    file: lib/Math/Symbolic/Custom/Pattern.pm
    version: 1.10
  Math::Symbolic::Custom::Pattern::Export:
    file: lib/Math/Symbolic/Custom/Pattern/Export.pm
    version: 1.10
generated_by: Module::Build version 0.2608
